### ISSUE TITLE
TABANG DILI MA BUILD

### ISSUE THREAD

**Issue by jspenya** [COE11-USTP-CEA/Javadings-not-vadings#1]
tabang
![screenshot from 2017-02-17 15 02 21](https://cloud.githubusercontent.com/assets/24237429/23055696/275b21b6-f522-11e6-9965-e1f6c348b59d.png)

**Comment by killertilapia** [comment]
Did you install the latest JFK and is using it? Because you could be
running openjdk - because Ubuntu.

Also did the mvn install command finish successfully?

**Comment by penyakamaayo** [comment]
`Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ TepenSpark ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] 
[INFO] --- maven-install-plugin:2.3:install (default-install) @ TepenSpark ---
[INFO] Installing /home/stephen/Desktop/sparkJava/Javadings-not-vadings/target/TepenSpark-1.0-SNAPSHOT.jar to /home/stephen/.m2/repository/com/sample/TepenSpark/1.0-SNAPSHOT/TepenSpark-1.0-SNAPSHOT.jar
[INFO] Installing /home/stephen/Desktop/sparkJava/Javadings-not-vadings/pom.xml to /home/stephen/.m2/repository/com/sample/TepenSpark/1.0-SNAPSHOT/TepenSpark-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.699s
[INFO] Finished at: Fri Feb 17 21:32:56 PHT 2017
[INFO] Final Memory: 7M/149M
[INFO] ------------------------------------------------------------------------
`

Yes sir, I have the latest JDK installed. 

Also, yes sir, here's what i got

**Comment by jspenya** [comment]
I currently have jdk 1.6 sir. I am downloading jdk 1.8 at the moment

**Comment by jspenya** [comment]
Jdk 1.8 up and running.

mvn install command says: Build success

however, when i run mvn exec:java, here's what happens
![error](https://cloud.githubusercontent.com/assets/24237429/23069255/b07a33e4-f561-11e6-9e5c-e940cb1cf3f6.png)

**Comment by BrickY1816** [comment]
Salamat na build rajud.

**Comment by jspenya** [comment]
@BrickY1816 pero dili pa mo run :cry:

**Comment by killertilapia** [comment]
Looks your trying to run a class named MainNgaClass, if you cloned the
demospark repo properly, there should be NO FILE named MainNgaClass.

**Comment by jspenya** [comment]
@killertilapia I tried to create a new project sir, with my main class named MainNgaClass and, modified the path to my main class in my pom file. Hehe
